### PR TITLE
Provide optional override for stack configs

### PR DESCRIPTION
**Pull request by xldenis**
This lets the user specify a `stack_config_file` parameter for the project which is used to override the default stack yaml.

idk it's the simplest / cleanest way to implement this within the codebase.

### CODE REVIEW

**Comment by xldenis** [comment]
I'm not sure how to get it to appear in the command list, I've added it to `Default.sublime-commands` but it doesnt seem to have an effect.

**Comment by bscottm** [comment]
@xldenis: If the name of the Python class is SublimeHaskellStackYamlThingy, ST generates the name "sublime_haskell_stack_yaml_thingy" (all lower, snake case) that is the name of the command.

Or, in your case, "sublime_haskell_stack_config_switch"

**Comment by bscottm** [comment]
@xldenis: We should probably mention this in the SublimeHaskell Editing Guide.

**Comment by bscottm** [comment]
@xldenis: And we should probably give the 1.2.0 release about a week for people to update before releasing this update.

**Comment by xldenis** [comment]
That sounds reasonable to me.

**Pull request merged**
